name: CI/CD Pipeline for Facial Emotion Recognition

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sebassalvaradoo/deep_learning:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push sebassalvaradoo/deep_learning:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            if docker ps | grep -q deep_learning; then
              docker stop deep_learning
              docker rm deep_learning
            fi
            docker pull sebassalvaradoo/deep_learning:latest
            docker run -d --name deep_learning -p 8000:8000 sebassalvaradoo/deep_learning:latest
